class SettingsDB(object):
    MIN_NAME_LENGTH = 3
    MAX_NAME_LENGTH = 32
    MAX_EMAIL_LENGTH = 32
    MIN_PASSWORD_LENGTH = 6
    MAX_PASSWORD_LENGTH = 32
    MAX_TASK_MESSAGE_LENGTH = 2048
    MAX_TASK_PRICE_TITLE = 128
    MAX_OPEN_TASKS_BY_OPERATOR = 10

    MESSAGES_CHUNK_SIZE = 50